Created header and headline
Xecyc/My-portfolio pull request #1
Opened 2023-02-18 02:51 UTC by Xecyc

This is the first pull request of My-Portfolio project, I created the header and the headline, I did it as close as I could to the original mobile template with the current tools and knowledge. There are a few details I would like to add: 

- I had no idea how to recreate the background image perfectly.
- There are plenty of lines of code that can be removed.
- Updated the README file.

2023-02-18 02:59 UTC, joel-kalema reviewed
Hi @Xecyc 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

- [ ] You have submitted a project that has linters that does not checked, make sure you solve them and the ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-22 02:18 UTC, Kossi-stack requested changes
## Hi @Xecyc,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-22 02:18 UTC, Kossi-stack commented on index.html
> +      <div class="logo-box">
- [ ] Kindly use a tag for the logo
- [ ] Because of three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-02-22 02:18 UTC, Kossi-stack commented on index.html
> +        <div class="ham-box">
- [ ] Kindly use the nav tag for the hamburger
- [ ] 1. The `nav` tag is for semantics reasons and the right position for convention and user experience for mobile devices.

2023-02-22 02:18 UTC, Kossi-stack commented on index.html
> +    <section class="social-media">
- [ ] Kindly make sure the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag).

* Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.
see image below

<img width="1107" alt="Screenshot 2023-02-21 at 18 09 31" src="https://user-images.githubusercontent.com/81444338/220503431-c58542cc-5b20-4675-b483-5d11d80e353e.png">

2023-02-22 12:34 UTC, Ibizugbe requested changes
Hi @Xecyc 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/220619823-ff0559f1-6fcb-4e9b-8087-eda239d897a4.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Linters are passing👍
- [x] Github flow has been used👍


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Nice job setting up your MIT License👍. but currently, the contents haven't been personalised😉 this will give your project a less professional look😉 Kindly include your details where necessary in the license😎
<img width="788" alt="MIT" src="https://user-images.githubusercontent.com/64643995/220620971-76312dbd-176d-4a59-b26b-9b13eda501b8.png">

- _see comments under review_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 12:34 UTC, Ibizugbe commented on index.html
> +      </nav>
I can see you put in a lot of effort implementing the changes requested by the previous reviewer, Nice job👍👍 But I think you are still making a mistake😉 I don't think there is any need for a nested `nav` here😉 you can take away the nav tag around the hamburger bar or take away the `nav` tag at line 15, just as the previous reviewer requested😉 in all, ensure to use just one `nav` tag😉😉

2023-02-22 12:34 UTC, Ibizugbe commented on index.html
> +      <h2>I'm a software developer</h2>
[optional] I think it makes more sense to use just one `header` tag (`h1` precisely) to wrap your intro text😉 you can then use a `span` or a `div` within the `H1` so as to implement your styling😉 This makes more sense semantically as they are all Intro texts and should all be wrapped in the main heading😉

you can have something like this instead😉
`<h1>Hey there. I'm Edu <div class="add-a-class-for-styling😉">I'm a software developer</div></h1>`

2023-02-22 13:20 UTC, gemmen29 approved these changes
Hi @Xecyc, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 13:20 UTC, gemmen29 commented on index.html
> +      </ul>
- [ ] [OPTIONAL] Kindly remove the small black dots at the beginning of each item of the `ul` of social media icons.
![image](https://user-images.githubusercontent.com/24703171/220631270-be8cef3d-1d29-4910-a59b-c6541e8accbe.png)
### Hint:
You can do that by giving the ul the following CSS
``` CSS
list-style: none;
```

2023-02-22 14:01 UTC, merged